"""Профили для генерации мужских и женских эльфийских имен."""

from name_generator.models import RussianNameProfile, WeightedValue

ELF_MALE = RussianNameProfile(
    consonants=[
        WeightedValue('л', 30),
        WeightedValue('р', 25),
        WeightedValue('н', 20),
        WeightedValue('с', 10),
        WeightedValue('в', 6),
        WeightedValue('м', 6),
        WeightedValue('т', 5),
    ],
    vowels=[
        WeightedValue('а', 20),
        WeightedValue('э', 18),
        WeightedValue('и', 25),
        WeightedValue('е', 15),
        WeightedValue('о', 7),
    ],
    onset_clusters=[
        WeightedValue('тр', 8),
        WeightedValue('сл', 6),
    ],
    coda_clusters=[
        WeightedValue('ль', 10),
        WeightedValue('рн', 5),
    ],
    start_syllables=[
        WeightedValue('Эл', 22),
        WeightedValue('Ли', 18),
        WeightedValue('Аэ', 12),
        WeightedValue('Ил', 14),
        WeightedValue('Та', 9),
        WeightedValue('Са', 9),
        WeightedValue('Эри', 9),
        WeightedValue('Лаэ', 7),
        WeightedValue('Нэ', 7),
        WeightedValue('Ари', 8),
        WeightedValue('Си', 6),
        WeightedValue('Ваэ', 4),
    ],
    middle_syllables=[
        WeightedValue('ри', 18),
        WeightedValue('ли', 17),
        WeightedValue('ра', 14),
        WeightedValue('ни', 10),
        WeightedValue('э', 5),
        WeightedValue('ла', 10),
        WeightedValue('ре', 8),
        WeightedValue('но', 6),
        WeightedValue('си', 6),
        WeightedValue('ви', 5),
        WeightedValue('эль', 4),
    ],
    end_syllables=[
        WeightedValue('ион', 18),
        WeightedValue('ир', 22),
        WeightedValue('ор', 10),
        WeightedValue('ан', 18),
        WeightedValue('ис', 10),
        WeightedValue('эль', 8),
        WeightedValue('ар', 12),
        WeightedValue('ен', 8),
        WeightedValue('иан', 8),
        WeightedValue('орин', 5),
        WeightedValue('аэль', 4),
    ],
    patterns=[
        WeightedValue('SE', 35),
        WeightedValue('SME', 45),
        WeightedValue('SMME', 8),
        # Редкие полностью процедурные формы.
        WeightedValue('CVCVE', 5),
        WeightedValue('KVCE', 2),
    ],
    min_length=4,
    max_length=13,
    max_consonants_in_row=2,
    max_vowels_in_row=2,
    forbidden_combinations=[
        'ааа',
        'иии',
        'эээ',
        'ллл',
        'ррр',
        'ннн',
    ],
    replacement_rules={
        'ии': 'и',
        'ээ': 'э',
        'аа': 'а',
        'ллл': 'лл',
        'ррр': 'рр',
        'ннн': 'нн',
    },
    apostrophe_chance=0.015,
)


ELF_FEMALE = RussianNameProfile(
    consonants=[
        WeightedValue('л', 30),
        WeightedValue('р', 20),
        WeightedValue('н', 25),
        WeightedValue('с', 15),
        WeightedValue('в', 5),
        WeightedValue('м', 10),
        WeightedValue('т', 4),
    ],
    vowels=[
        WeightedValue('а', 30),
        WeightedValue('э', 18),
        WeightedValue('и', 25),
        WeightedValue('е', 15),
        WeightedValue('о', 4),
    ],
    onset_clusters=[
        WeightedValue('сл', 7),
    ],
    coda_clusters=[
        WeightedValue('ль', 12),
    ],
    start_syllables=[
        WeightedValue('Эл', 18),
        WeightedValue('Ли', 22),
        WeightedValue('Аэ', 18),
        WeightedValue('Ил', 9),
        WeightedValue('Са', 13),
        WeightedValue('Эли', 12),
        WeightedValue('Лаэ', 9),
        WeightedValue('Нэ', 8),
        WeightedValue('Ми', 8),
        WeightedValue('Ари', 8),
        WeightedValue('Сиэ', 5),
    ],
    middle_syllables=[
        WeightedValue('ри', 14),
        WeightedValue('ли', 22),
        WeightedValue('на', 18),
        WeightedValue('ра', 14),
        WeightedValue('э', 8),
        WeightedValue('ла', 14),
        WeightedValue('ми', 8),
        WeightedValue('ни', 10),
        WeightedValue('си', 6),
        WeightedValue('ари', 7),
        WeightedValue('эли', 5),
    ],
    end_syllables=[
        WeightedValue('иэль', 18),
        WeightedValue('ара', 17),
        WeightedValue('ина', 17),
        WeightedValue('эль', 14),
        WeightedValue('ира', 17),
        WeightedValue('иэль', 8),
        WeightedValue('ана', 10),
        WeightedValue('эла', 9),
        WeightedValue('лия', 10),
        WeightedValue('иара', 5),
        WeightedValue('эри', 5),
    ],
    patterns=[
        WeightedValue('SE', 30),
        WeightedValue('SME', 50),
        WeightedValue('SMME', 12),
        # Небольшая доля менее шаблонных имён.
        WeightedValue('CVCVE', 5),
        WeightedValue('SVE', 3),
    ],
    min_length=4,
    max_length=14,
    max_consonants_in_row=2,
    max_vowels_in_row=2,
    forbidden_combinations=[
        'ааа',
        'иии',
        'эээ',
        'ллл',
        'ррр',
        'ннн',
    ],
    replacement_rules={
        'ии': 'и',
        'ээ': 'э',
        'аа': 'а',
        'ллл': 'лл',
        'ррр': 'рр',
        'ннн': 'нн',
    },
    apostrophe_chance=0.015,
)
