"""Профиль генерации названий для городов орков."""

from name_generator.models import RussianNameProfile, WeightedValue

ORC_CITY = RussianNameProfile(
    consonants=[
        WeightedValue('г', 30),
        WeightedValue('к', 27),
        WeightedValue('р', 32),
        WeightedValue('д', 20),
        WeightedValue('т', 16),
        WeightedValue('м', 10),
        WeightedValue('н', 12),
        WeightedValue('х', 8),
        WeightedValue('б', 8),
        WeightedValue('з', 6),
    ],
    vowels=[
        WeightedValue('а', 40),
        WeightedValue('о', 35),
        WeightedValue('у', 20),
        WeightedValue('ы', 5),
    ],
    onset_clusters=[
        WeightedValue('гр', 27),
        WeightedValue('кр', 25),
        WeightedValue('др', 16),
        WeightedValue('тр', 12),
        WeightedValue('хр', 8),
        WeightedValue('згр', 4),
        WeightedValue('бр', 7),
        WeightedValue('гн', 6),
        WeightedValue('кх', 5),
    ],
    coda_clusters=[
        WeightedValue('рг', 20),
        WeightedValue('рк', 18),
        WeightedValue('нд', 12),
        WeightedValue('нг', 12),
        WeightedValue('рт', 10),
        WeightedValue('гд', 7),
        WeightedValue('кт', 6),
        WeightedValue('рх', 5),
    ],
    start_syllables=[
        WeightedValue('Гор', 15),
        WeightedValue('Гар', 13),
        WeightedValue('Краг', 18),
        WeightedValue('Дур', 15),
        WeightedValue('Мор', 11),
        WeightedValue('Ур', 14),
        WeightedValue('Торг', 12),
        WeightedValue('Хар', 9),
        WeightedValue('Грум', 8),
        WeightedValue('Браг', 9),
        WeightedValue('Гром', 8),
        WeightedValue('Кхар', 8),
        WeightedValue('Драг', 9),
        WeightedValue('Нарг', 8),
        WeightedValue('Зуг', 7),
        WeightedValue('Крум', 7),
    ],
    middle_syllables=[
        WeightedValue('га', 12),
        WeightedValue('гор', 15),
        WeightedValue('дур', 16),
        WeightedValue('рак', 14),
        WeightedValue('тар', 10),
        WeightedValue('мар', 8),
        WeightedValue('ур', 10),
        WeightedValue('гур', 10),
        WeightedValue('кар', 9),
        WeightedValue('дог', 8),
        WeightedValue('раг', 10),
        WeightedValue('кру', 6),
        WeightedValue('нар', 7),
    ],
    end_syllables=[
        # Явно городские / крепостные окончания
        WeightedValue('град', 12),
        WeightedValue('гар', 13),
        WeightedValue('дор', 12),
        WeightedValue('рак', 11),
        WeightedValue('дур', 10),
        WeightedValue('гор', 10),
        WeightedValue('тар', 8),
        WeightedValue('кхар', 6),
        # Более тяжёлые орочьи топонимы
        WeightedValue('гарт', 8),
        WeightedValue('бург', 4),
        WeightedValue('рок', 8),
        WeightedValue('грум', 6),
        WeightedValue('раг', 8),
        WeightedValue('круг', 5),
        WeightedValue('дар', 7),
    ],
    patterns=[
        WeightedValue('SE', 30),
        WeightedValue('SME', 45),
        WeightedValue('SMME', 15),
        # Более грубые процедурные формы
        WeightedValue('KVDE', 5),
        WeightedValue('KVCDE', 5),
    ],
    min_length=5,
    max_length=16,
    max_consonants_in_row=3,
    max_vowels_in_row=1,
    forbidden_combinations=[
        'аа',
        'оо',
        'уу',
        'ыы',
        'ррр',
        'ггг',
        'ккк',
    ],
    replacement_rules={
        'аа': 'а',
        'оо': 'о',
        'уу': 'у',
        'ыы': 'ы',
        'рр': 'р',
        'ггг': 'гг',
        'ккк': 'кк',
    },
    apostrophe_chance=0.02,
)
