"""Профиль генерации названий для стран орков."""

from name_generator.models import RussianNameProfile, WeightedValue

ORC_COUNTRY = RussianNameProfile(
    consonants=[
        WeightedValue('г', 27),
        WeightedValue('к', 25),
        WeightedValue('р', 35),
        WeightedValue('д', 20),
        WeightedValue('т', 16),
        WeightedValue('м', 12),
        WeightedValue('н', 12),
        WeightedValue('з', 7),
        WeightedValue('х', 8),
        WeightedValue('б', 7),
    ],
    vowels=[
        WeightedValue('а', 38),
        WeightedValue('о', 32),
        WeightedValue('у', 25),
        WeightedValue('ы', 5),
    ],
    onset_clusters=[
        WeightedValue('гр', 25),
        WeightedValue('кр', 22),
        WeightedValue('др', 18),
        WeightedValue('тр', 12),
        WeightedValue('хр', 8),
        WeightedValue('бр', 7),
        WeightedValue('згр', 4),
        WeightedValue('гн', 5),
    ],
    coda_clusters=[
        WeightedValue('рг', 20),
        WeightedValue('рк', 18),
        WeightedValue('нд', 12),
        WeightedValue('нг', 12),
        WeightedValue('рт', 9),
        WeightedValue('гд', 6),
        WeightedValue('рх', 5),
    ],
    start_syllables=[
        WeightedValue('Гар', 12),
        WeightedValue('Гор', 12),
        WeightedValue('Кра', 18),
        WeightedValue('Дур', 15),
        WeightedValue('Мор', 12),
        WeightedValue('Ур', 15),
        WeightedValue('Тар', 10),
        WeightedValue('Хар', 8),
        WeightedValue('Гру', 9),
        WeightedValue('Нарг', 8),
        WeightedValue('Браг', 7),
        WeightedValue('Зуг', 7),
        WeightedValue('Кхар', 7),
        WeightedValue('Драг', 8),
    ],
    middle_syllables=[
        WeightedValue('гар', 15),
        WeightedValue('дур', 17),
        WeightedValue('рак', 15),
        WeightedValue('гор', 12),
        WeightedValue('тар', 10),
        WeightedValue('нар', 9),
        WeightedValue('мар', 7),
        WeightedValue('гур', 10),
        WeightedValue('дар', 8),
        WeightedValue('раг', 10),
        WeightedValue('кру', 6),
        WeightedValue('хар', 7),
    ],
    end_syllables=[
        # Более "государственные" окончания
        WeightedValue('гар', 12),
        WeightedValue('гур', 10),
        WeightedValue('дар', 10),
        WeightedValue('дор', 8),
        WeightedValue('тар', 8),
        WeightedValue('хар', 8),
        # Тяжёлые орочьи окончания
        WeightedValue('ар', 11),
        WeightedValue('ор', 10),
        WeightedValue('дур', 9),
        WeightedValue('рак', 8),
        WeightedValue('гор', 8),
        WeightedValue('ург', 7),
        WeightedValue('арк', 7),
        # Редкая адаптированная форма
        WeightedValue('ия', 3),
    ],
    patterns=[
        WeightedValue('SE', 25),
        WeightedValue('SME', 50),
        WeightedValue('SMME', 15),
        # Более древние и грубые формы
        WeightedValue('KVME', 5),
        WeightedValue('KVMDE', 5),
    ],
    min_length=5,
    max_length=17,
    max_consonants_in_row=3,
    max_vowels_in_row=1,
    forbidden_combinations=[
        'аа',
        'оо',
        'уу',
        'ыы',
        'ррр',
        'ггг',
        'ккк',
    ],
    replacement_rules={
        'аа': 'а',
        'оо': 'о',
        'уу': 'у',
        'ыы': 'ы',
        'рр': 'р',
        'ггг': 'гг',
        'ккк': 'кк',
    },
    apostrophe_chance=0.015,
)
