"""Профили для генерации мужских и женских имен людей."""

from name_generator.models import RussianNameProfile, WeightedValue

HUMAN_MALE = RussianNameProfile(
    consonants=[
        WeightedValue('б', 8),
        WeightedValue('в', 14),
        WeightedValue('г', 8),
        WeightedValue('д', 14),
        WeightedValue('к', 10),
        WeightedValue('л', 24),
        WeightedValue('м', 18),
        WeightedValue('н', 25),
        WeightedValue('р', 30),
        WeightedValue('с', 18),
        WeightedValue('т', 20),
        WeightedValue('ф', 4),
        WeightedValue('х', 3),
        WeightedValue('з', 7),
        WeightedValue('п', 6),
    ],
    vowels=[
        WeightedValue('а', 32),
        WeightedValue('е', 20),
        WeightedValue('и', 22),
        WeightedValue('о', 20),
        WeightedValue('у', 6),
    ],
    onset_clusters=[
        WeightedValue('бр', 10),
        WeightedValue('др', 12),
        WeightedValue('кр', 7),
        WeightedValue('тр', 10),
        WeightedValue('гр', 5),
        WeightedValue('ст', 10),
        WeightedValue('пр', 6),
        WeightedValue('ск', 5),
    ],
    coda_clusters=[
        WeightedValue('рн', 8),
        WeightedValue('рт', 8),
        WeightedValue('нд', 10),
        WeightedValue('ст', 8),
        WeightedValue('ль', 10),
        WeightedValue('н', 20),
        WeightedValue('р', 20),
        WeightedValue('рд', 6),
        WeightedValue('лд', 4),
    ],
    start_syllables=[
        WeightedValue('Аль', 12),
        WeightedValue('Ар', 18),
        WeightedValue('Бер', 10),
        WeightedValue('Вар', 13),
        WeightedValue('Дар', 15),
        WeightedValue('Кал', 10),
        WeightedValue('Лор', 12),
        WeightedValue('Мар', 18),
        WeightedValue('Рен', 14),
        WeightedValue('Сер', 12),
        WeightedValue('Тар', 10),
        WeightedValue('Эд', 8),
        WeightedValue('Эр', 12),
        WeightedValue('Вел', 8),
        WeightedValue('Бран', 8),
        WeightedValue('Гар', 8),
        WeightedValue('Дел', 7),
        WeightedValue('Кор', 8),
        WeightedValue('Нор', 9),
        WeightedValue('Рад', 7),
        WeightedValue('Тор', 7),
        WeightedValue('Фер', 5),
    ],
    middle_syllables=[
        WeightedValue('ан', 17),
        WeightedValue('ар', 15),
        WeightedValue('ен', 15),
        WeightedValue('ер', 13),
        WeightedValue('ил', 12),
        WeightedValue('ор', 12),
        WeightedValue('ин', 14),
        WeightedValue('ел', 10),
        WeightedValue('ри', 10),
        WeightedValue('да', 5),
        WeightedValue('ал', 9),
        WeightedValue('он', 8),
        WeightedValue('ра', 7),
        WeightedValue('ми', 6),
        WeightedValue('тер', 5),
        WeightedValue('вин', 5),
    ],
    end_syllables=[
        WeightedValue('ан', 18),
        WeightedValue('ар', 15),
        WeightedValue('ен', 16),
        WeightedValue('ер', 13),
        WeightedValue('ин', 15),
        WeightedValue('ор', 12),
        WeightedValue('ель', 8),
        WeightedValue('ис', 7),
        WeightedValue('он', 10),
        WeightedValue('ир', 10),
        WeightedValue('ий', 7),
        WeightedValue('ас', 6),
        WeightedValue('ус', 5),
        WeightedValue('ард', 6),
        WeightedValue('ерт', 5),
    ],
    patterns=[
        WeightedValue('SE', 32),
        WeightedValue('SME', 40),
        WeightedValue('SMME', 6),
        WeightedValue('CVCVC', 9),
        WeightedValue('KVC', 6),
        WeightedValue('CVCE', 7),
    ],
    min_length=4,
    max_length=12,
    max_consonants_in_row=2,
    max_vowels_in_row=2,
    forbidden_combinations=[
        'ааа',
        'еее',
        'иии',
        'ооо',
        'ууу',
        'кг',
        'гк',
        'тд',
        'дт',
        'бп',
        'пб',
        'ррр',
        'ннн',
    ],
    replacement_rules={
        'аа': 'а',
        'ее': 'е',
        'ии': 'и',
        'оо': 'о',
        'уу': 'у',
        'рр': 'р',
        'ннн': 'нн',
        'ллл': 'лл',
    },
    apostrophe_chance=0.0,
)


HUMAN_FEMALE = RussianNameProfile(
    consonants=[
        WeightedValue('в', 12),
        WeightedValue('д', 8),
        WeightedValue('к', 7),
        WeightedValue('л', 28),
        WeightedValue('м', 20),
        WeightedValue('н', 26),
        WeightedValue('р', 24),
        WeightedValue('с', 18),
        WeightedValue('т', 14),
        WeightedValue('з', 7),
        WeightedValue('б', 5),
    ],
    vowels=[
        WeightedValue('а', 38),
        WeightedValue('е', 20),
        WeightedValue('и', 24),
        WeightedValue('о', 10),
        WeightedValue('у', 3),
        WeightedValue('э', 5),
    ],
    onset_clusters=[
        WeightedValue('бр', 5),
        WeightedValue('др', 5),
        WeightedValue('ст', 8),
        WeightedValue('тр', 4),
        WeightedValue('сл', 7),
        WeightedValue('кр', 3),
    ],
    coda_clusters=[
        WeightedValue('ль', 12),
        WeightedValue('н', 20),
        WeightedValue('р', 12),
        WeightedValue('ст', 5),
        WeightedValue('нд', 4),
    ],
    start_syllables=[
        WeightedValue('Али', 15),
        WeightedValue('Ара', 12),
        WeightedValue('Эли', 17),
        WeightedValue('Ила', 9),
        WeightedValue('Ли', 13),
        WeightedValue('Мари', 18),
        WeightedValue('Са', 12),
        WeightedValue('Сели', 10),
        WeightedValue('Ве', 8),
        WeightedValue('Лора', 12),
        WeightedValue('Нари', 10),
        WeightedValue('Те', 7),
        WeightedValue('Адел', 8),
        WeightedValue('Вал', 7),
        WeightedValue('Ири', 9),
        WeightedValue('Кари', 8),
        WeightedValue('Мела', 7),
        WeightedValue('Рена', 8),
        WeightedValue('Сера', 8),
        WeightedValue('Эра', 6),
    ],
    middle_syllables=[
        WeightedValue('ли', 18),
        WeightedValue('ри', 17),
        WeightedValue('на', 20),
        WeightedValue('ла', 15),
        WeightedValue('ми', 10),
        WeightedValue('си', 8),
        WeightedValue('да', 8),
        WeightedValue('э', 5),
        WeightedValue('не', 9),
        WeightedValue('ра', 12),
        WeightedValue('ви', 6),
        WeightedValue('ел', 7),
        WeightedValue('ана', 5),
    ],
    end_syllables=[
        WeightedValue('а', 22),
        WeightedValue('ия', 16),
        WeightedValue('ина', 16),
        WeightedValue('ира', 15),
        WeightedValue('ела', 11),
        WeightedValue('эна', 9),
        WeightedValue('ана', 13),
        WeightedValue('ис', 5),
        WeightedValue('ена', 10),
        WeightedValue('ара', 10),
        WeightedValue('ора', 7),
        WeightedValue('ель', 6),
        WeightedValue('ея', 6),
    ],
    patterns=[
        WeightedValue('SE', 34),
        WeightedValue('SME', 44),
        WeightedValue('SMME', 7),
        WeightedValue('CVCVCV', 9),
        WeightedValue('CVCE', 6),
    ],
    min_length=4,
    max_length=13,
    max_consonants_in_row=2,
    max_vowels_in_row=2,
    forbidden_combinations=[
        'ааа',
        'еее',
        'иии',
        'ооо',
        'кг',
        'гк',
        'тд',
        'дт',
        'ррр',
        'ннн',
    ],
    replacement_rules={
        'аа': 'а',
        'ее': 'е',
        'ии': 'и',
        'оо': 'о',
        'рр': 'р',
        'ннн': 'нн',
        'ллл': 'лл',
    },
    apostrophe_chance=0.0,
)
