"""Профиль для генерации фамилий людей."""

from name_generator.models import RussianNameProfile, WeightedValue

HUMAN_SURNAME = RussianNameProfile(
    consonants=[
        WeightedValue('б', 7),
        WeightedValue('в', 15),
        WeightedValue('д', 12),
        WeightedValue('к', 12),
        WeightedValue('л', 20),
        WeightedValue('м', 14),
        WeightedValue('н', 18),
        WeightedValue('р', 26),
        WeightedValue('с', 18),
        WeightedValue('т', 16),
        WeightedValue('г', 8),
        WeightedValue('п', 6),
        WeightedValue('з', 5),
    ],
    vowels=[
        WeightedValue('а', 30),
        WeightedValue('е', 22),
        WeightedValue('и', 18),
        WeightedValue('о', 22),
        WeightedValue('у', 8),
    ],
    onset_clusters=[
        WeightedValue('бр', 8),
        WeightedValue('др', 8),
        WeightedValue('кр', 8),
        WeightedValue('ст', 10),
        WeightedValue('тр', 7),
        WeightedValue('гр', 6),
        WeightedValue('пр', 5),
        WeightedValue('ск', 5),
    ],
    coda_clusters=[
        WeightedValue('рд', 8),
        WeightedValue('рн', 8),
        WeightedValue('ль', 10),
        WeightedValue('ст', 10),
        WeightedValue('н', 14),
        WeightedValue('рт', 6),
        WeightedValue('ск', 5),
    ],
    start_syllables=[
        WeightedValue('Арден', 8),
        WeightedValue('Бел', 12),
        WeightedValue('Вар', 12),
        WeightedValue('Дор', 11),
        WeightedValue('Кел', 9),
        WeightedValue('Лор', 14),
        WeightedValue('Мар', 14),
        WeightedValue('Рен', 12),
        WeightedValue('Сар', 10),
        WeightedValue('Тер', 10),
        WeightedValue('Вел', 10),
        WeightedValue('Бран', 9),
        WeightedValue('Гар', 8),
        WeightedValue('Дал', 8),
        WeightedValue('Кар', 9),
        WeightedValue('Нор', 9),
        WeightedValue('Рав', 7),
        WeightedValue('Бер', 8),
        WeightedValue('Мор', 8),
        WeightedValue('Стен', 6),
        WeightedValue('Тор', 7),
    ],
    middle_syllables=[
        WeightedValue('ен', 15),
        WeightedValue('ар', 15),
        WeightedValue('ор', 12),
        WeightedValue('ел', 12),
        WeightedValue('ин', 10),
        WeightedValue('ер', 10),
        WeightedValue('ов', 12),
        WeightedValue('ев', 8),
        WeightedValue('ан', 10),
        WeightedValue('ол', 7),
        WeightedValue('ир', 7),
        WeightedValue('енс', 5),
    ],
    end_syllables=[
        # Нейтральные фамильные окончания
        WeightedValue('ар', 10),
        WeightedValue('ен', 10),
        WeightedValue('ер', 10),
        WeightedValue('ор', 9),
        WeightedValue('ин', 11),
        WeightedValue('ель', 7),
        WeightedValue('ан', 9),
        WeightedValue('ард', 6),
        # Более явно фамильные формы
        WeightedValue('ов', 12),
        WeightedValue('ев', 9),
        WeightedValue('ин', 8),
        WeightedValue('сен', 7),
        WeightedValue('сон', 6),
        WeightedValue('ман', 7),
        WeightedValue('берг', 5),
        WeightedValue('дорф', 4),
        WeightedValue('ский', 5),
    ],
    patterns=[
        WeightedValue('SE', 55),
        WeightedValue('SME', 35),
        WeightedValue('SMME', 5),
        # Небольшая доля процедурных фамилий
        WeightedValue('CVCE', 3),
        WeightedValue('KVCE', 2),
    ],
    min_length=4,
    max_length=15,
    max_consonants_in_row=3,
    max_vowels_in_row=2,
    forbidden_combinations=[
        'ааа',
        'еее',
        'иии',
        'ооо',
        'ууу',
        'ррр',
        'ннн',
        'ллл',
        'ттт',
    ],
    replacement_rules={
        'аа': 'а',
        'ее': 'е',
        'ии': 'и',
        'оо': 'о',
        'уу': 'у',
        'рр': 'р',
        'ннн': 'нн',
        'ллл': 'лл',
        'ттт': 'тт',
    },
    apostrophe_chance=0.002,
)
